name: Android CI

on:
  push:
    branches:
      - '**'        # matches every branch

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Unit tests
        run: ./gradlew testDevelopDebugUnitTest --stacktrace

  build:
    name: Build
    needs: [ test ]
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v3

      - name: set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (dev debug)
        run: ./gradlew buildDevelopDebugPreBundle --stacktrace

      - run: echo "Build status report=${{ job.status }}."

  develop:
    name: Deploy on branch Develop
    needs: [ build ]
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    container: alvrme/alpine-android:android-33-jdk11

    steps:
      - uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDevelopDebug

      - name: Upload APK
        run: |
          extras fastlane
          fastlane android distribute_firebase
